import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[window]
dynamic_padding = true
# opacity = 0.9
option_as_alt = "Both"
startup_mode = "Maximized"

[font]
normal = {  family = "FiraCode Nerd Font", style = "Regular"  }
size = 12
