theme = "onedark"

[editor]
mouse = false
true-color = true
cursorline = true
rulers = [120]
bufferline = "always"
color-modes = true

[editor.statusline]
left = ["mode", "read-only-indicator"]
center = ["file-modification-indicator", "file-name", "file-encoding"]
right = ["diagnostics", "selections", "position", "position-percentage","file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
# g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
